#!/usr/bin/env python3

def p_num(num):

    c = True

    for i in range(1,num):
        if(num == 1):
            c = True
            break
        elif(num%i == 0 and (i != num and i != 1 )):
            c = False
            break
        else:
            c = True

    return c

num = int(input("Enter the number you want to check for prime number \n"))

if(p_num(num)):
    print(num," is a prime number. \n")
else:
    print(num, " is not a prime number. \n")
